DROP DATABASE IF EXISTS phpCRUD; -- for testing  => REMOVE BEFORE DEPLOYMENT

CREATE DATABASE phpCRUD;

USE phpCRUD;

CREATE TABLE permittedUsers(
	id				INT 			PRIMARY KEY AUTO_INCREMENT,
	username		VARCHAR(50)		UNIQUE,
	password_hash	VARCHAR(255)	NOT NULL,	
	permissions		INT				DEFAULT 1,
	dateCreated		DATETIME		DEFAULT CURRENT_TIMESTAMP(),
	updateDate		DATETIME		DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);

CREATE TABLE person(
	id 				INT				PRIMARY KEY AUTO_INCREMENT,
	name			VARCHAR(50),
	surname			VARCHAR(50),
	email			VARCHAR(255) 	UNIQUE,
	dateCreated		DATETIME		DEFAULT CURRENT_TIMESTAMP(),
	updateDate		DATETIME		DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);

INSERT INTO permittedUsers (username, password_hash, permissions)
	VALUES
	('Admin', '$2y$10$jSwhTW6FNpBQsgFxl4OPGeQC.wH1AXn3yOoA23RZ5bLY.LzByl6Zq', 3),       -- password is "pw1234" for all users
	('Service', '$2y$10$jSwhTW6FNpBQsgFxl4OPGeQC.wH1AXn3yOoA23RZ5bLY.LzByl6Zq', 2),
	('User', '$2y$10$jSwhTW6FNpBQsgFxl4OPGeQC.wH1AXn3yOoA23RZ5bLY.LzByl6Zq', 1);
	
	
CREATE TABLE login_attempts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ip_address VARCHAR(45) NOT NULL,
    username VARCHAR(50) NOT NULL,
    attempts INT NOT NULL DEFAULT 1,
    last_attempt DATETIME NOT NULL,
    UNIQUE KEY unique_attempt (ip_address, username),
    INDEX (last_attempt)
);

INSERT INTO person (name, surname, email) VALUES        -- 200 dummy entries for testing
('Lukas', 'Schmidt', 'lukas.schmidt@example.de'),
('Julia', 'Schmidt', 'j.schmidt@web.de'),
('Lukas', 'Fischer', 'l.fischer@gmail.com'),
('Julia', 'Fischer', 'julia.fischer88@web.de'),
('Finn', 'Weber', 'finn.weber@gmail.com'),
('Leonie', 'Weber', 'leonie.w@outlook.de'),
('Finn', 'Meyer', 'f.meyer@gmx.de'),
('Leonie', 'Meyer', 'leonie.meyer@outlook.de'),
('Noah', 'Wagner', 'noah_wagner@gmx.de'),
('Hannah', 'Wagner', 'h.wagner@t-online.de'),
('Noah', 'Becker', 'n.becker@live.com'),
('Hannah', 'Becker', 'hannah.becker@t-online.de'),
('Elias', 'Schulz', 'elias.schulz@live.com'),
('Sophia', 'Schulz', 'sophia.s@icloud.com'),
('Elias', 'Hoffmann', 'e.hoffmann@yahoo.de'),
('Sophia', 'Hoffmann', 'sophia.h@icloud.com'),
('Ben', 'Schäfer', 'ben.schaefer@yahoo.de'),
('Emma', 'Schäfer', 'emma.s@posteo.de'),
('Ben', 'Koch', 'b.koch@mailbox.org'),
('Emma', 'Koch', 'emma.koch@posteo.de'),
('Paul', 'Bauer', 'paul.bauer1@mailbox.org'),
('Mia', 'Bauer', 'mia.b@web.de'),
('Paul', 'Richter', 'p.richter@protonmail.com'),
('Mia', 'Richter', 'mia_richter_92@web.de'),
('Jonas', 'Klein', 'jonas.klein@protonmail.com'),
('Mila', 'Klein', 'mila.k@gmail.com'),
('Jonas', 'Wolf', 'j.wolf@t-online.de'),
('Mila', 'Wolf', 'mila.wolf@gmail.com'),
('Leon', 'Schröder', 'leon.schroeder@t-online.de'),
('Ella', 'Schröder', 'ella.s@outlook.com'),
('Leon', 'Neumann', 'l.neumann@gmx.net'),
('Ella', 'Neumann', 'ella_n@outlook.com'),
('Luis', 'Schwarz', 'luis.schwarz@gmx.net'),
('Lina', 'Schwarz', 'lina.s@me.com'),
('Luis', 'Zimmermann', 'l.zimmermann@freenet.de'),
('Lina', 'Zimmermann', 'lina.zimmermann@me.com'),
('Maximilian', 'Braun', 'max.braun@freenet.de'),
('Marie', 'Braun', 'marie.b@web.de'),
('Maximilian', 'Krüger', 'm.krueger@online.de'),
('Marie', 'Krüger', 'marie.krueger@web.de'),
('Felix', 'Hofmann', 'felix.hofmann@online.de'),
('Lea', 'Hofmann', 'lea.h@post.de'),
('Felix', 'Hartmann', 'f.hartmann@googlemail.com'),
('Lea', 'Hartmann', 'lea.hartmann@post.de'),
('Henry', 'Lange', 'henry_lange@googlemail.com'),
('Luisa', 'Lange', 'luisa.l@hotmail.com'),
('Henry', 'Schmitt', 'h.schmitt@fastmail.com'),
('Luisa', 'Schmitt', 'luisa.schmitt@hotmail.com'),
('Tim', 'Werner', 'tim.werner@fastmail.com'),
('Emilia', 'Werner', 'emilia.w@gmx.de'),
('Tim', 'Schmitz', 't.schmitz@t-online.de'),
('Emilia', 'Schmitz', 'emilia.schmitz@gmx.de'),
('David', 'Krause', 'david.krause@t-online.de'),
('Clara', 'Krause', 'clara.k@outlook.de'),
('David', 'Meier', 'd.meier@web.de'),
('Clara', 'Meier', 'clara_meier@outlook.de'),
('Julian', 'Lehmann', 'j.lehmann@web.de'),
('Sarah', 'Lehmann', 'sarah.l@gmail.com'),
('Julian', 'Schmid', 'j.schmid@proton.me'),
('Sarah', 'Schmid', 'sarah.schmid@gmail.com'),
('Samuel', 'Schulze', 'samuel.schulze@proton.me'),
('Lara', 'Schulze', 'lara.s@gmx.de'),
('Samuel', 'Maier', 's.maier@t-online.de'),
('Lara', 'Maier', 'lara.maier@gmx.de'),
('Jakob', 'Köhler', 'jakob.koehler@t-online.de'),
('Charlotte', 'Köhler', 'charlotte.k@web.de'),
('Jakob', 'Herrmann', 'j.herrmann@gmail.com'),
('Charlotte', 'Herrmann', 'charlotte.h@web.de'),
('Linus', 'König', 'linus_koenig@gmail.com'),
('Pia', 'König', 'pia.k@outlook.de'),
('Linus', 'Walter', 'l.walter@me.com'),
('Pia', 'Walter', 'pia.walter@outlook.de'),
('Matteo', 'Mayer', 'matteo.mayer@me.com'),
('Amelie', 'Mayer', 'amelie.m@yahoo.com'),
('Matteo', 'Huber', 'm.huber@live.de'),
('Amelie', 'Huber', 'amelie.huber@yahoo.com'),
('Oskar', 'Kaiser', 'oskar.kaiser@live.de'),
('Maja', 'Kaiser', 'maja.k@gmx.de'),
('Oskar', 'Fuchs', 'o.fuchs@web.de'),
('Maja', 'Fuchs', 'maja.fuchs@gmx.de'),
('Anton', 'Peters', 'anton.peters@web.de'),
('Sophie', 'Peters', 'sophie.p@t-online.de'),
('Anton', 'Lang', 'a.lang@gmail.com'),
('Sophie', 'Lang', 'sophie.lang@t-online.de'),
('Simon', 'Scholz', 'simon.scholz@gmail.com'),
('Marlene', 'Scholz', 'marlene.s@outlook.com'),
('Simon', 'Möller', 's.moeller@gmx.de'),
('Marlene', 'Möller', 'marlene.moeller@outlook.com'),
('Rafael', 'Weiß', 'rafael.weiss@gmx.de'),
('Victoria', 'Weiß', 'v.weiss@icloud.com'),
('Rafael', 'Jung', 'r.jung@web.de'),
('Victoria', 'Jung', 'v.jung@icloud.com'),
('Kilian', 'Hahn', 'kilian.hahn@web.de'),
('Jana', 'Hahn', 'jana.h@online.de'),
('Kilian', 'Schubert', 'k.schubert@gmail.com'),
('Jana', 'Schubert', 'jana.schubert@online.de'),
('Moritz', 'Vogel', 'moritz.vogel@gmail.com'),
('Elena', 'Vogel', 'elena.v@t-online.de'),
('Moritz', 'Friedrich', 'm.friedrich@outlook.de'),
('Elena', 'Friedrich', 'elena.f@t-online.de'),
('Hannes', 'Günther', 'hannes.guenther@outlook.de'),
('Isabel', 'Günther', 'isabel.g@gmx.net'),
('Hannes', 'Keller', 'h.keller@web.de'),
('Isabel', 'Keller', 'isabel.keller@gmx.net'),
('Fabian', 'Winkler', 'fabian.winkler@web.de'),
('Paula', 'Winkler', 'paula.w@gmail.com'),
('Fabian', 'Frank', 'f.frank@posteo.de'),
('Paula', 'Frank', 'paula.frank@gmail.com'),
('Adrian', 'Berger', 'adrian.berger@posteo.de'),
('Theresa', 'Berger', 'theresa.b@t-online.de'),
('Adrian', 'Roth', 'a.roth@outlook.com'),
('Theresa', 'Roth', 'theresa.roth@t-online.de'),
('Nico', 'Beck', 'nico.beck@outlook.com'),
('Mathilda', 'Beck', 'mathilda.b@gmx.de'),
('Nico', 'Lorenz', 'n.lorenz@web.de'),
('Mathilda', 'Lorenz', 'mathilda.lorenz@gmx.de'),
('Sebastian', 'Baumann', 's.baumann@web.de'),
('Lisa', 'Baumann', 'lisa.b@gmail.com'),
('Sebastian', 'Franke', 'seb.franke@t-online.de'),
('Lisa', 'Franke', 'lisa.franke@gmail.com'),
('Erik', 'Albrecht', 'erik.albrecht@t-online.de'),
('Melanie', 'Albrecht', 'melanie.a@online.de'),
('Erik', 'Schuster', 'e.schuster@gmx.de'),
('Melanie', 'Schuster', 'melanie.schuster@online.de'),
('Jan', 'Ludwig', 'jan.ludwig@gmx.de'),
('Katharina', 'Ludwig', 'k.ludwig@web.de'),
('Jan', 'Böhm', 'j.boehm@gmail.com'),
('Katharina', 'Böhm', 'k.boehm@web.de'),
('Dominik', 'Winter', 'dominik.winter@gmail.com'),
('Annika', 'Winter', 'annika.w@outlook.de'),
('Dominik', 'Kraus', 'd.kraus@t-online.de'),
('Annika', 'Kraus', 'annika.kraus@outlook.de'),
('Florian', 'Martin', 'florian.martin@t-online.de'),
('Nora', 'Martin', 'nora.m@gmx.net'),
('Florian', 'Schumacher', 'f.schumacher@web.de'),
('Nora', 'Schumacher', 'nora.schumacher@gmx.net'),
('Philipp', 'Vogt', 'philipp.vogt@web.de'),
('Johanna', 'Vogt', 'johanna.v@gmail.com'),
('Philipp', 'Otto', 'p.otto@posteo.de'),
('Johanna', 'Otto', 'johanna.otto@gmail.com'),
('Benedikt', 'Jäger', 'benedikt.jaeger@posteo.de'),
('Linda', 'Jäger', 'linda.j@t-online.de'),
('Benedikt', 'Stein', 'b.stein@outlook.com'),
('Linda', 'Stein', 'linda.stein@t-online.de'),
('Christian', 'Groß', 'christian.gross@outlook.com'),
('Valentina', 'Groß', 'valentina.g@gmx.de'),
('Christian', 'Sommer', 'c.sommer@web.de'),
('Valentina', 'Sommer', 'valentina.sommer@gmx.de'),
('Alexander', 'Seidel', 'alex.seidel@web.de'),
('Stella', 'Seidel', 'stella.s@gmail.com'),
('Alexander', 'Heinrich', 'a.heinrich@t-online.de'),
('Stella', 'Heinrich', 'stella.heinrich@gmail.com'),
('Marco', 'Brandt', 'marco.brandt@t-online.de'),
('Alina', 'Brandt', 'alina.b@outlook.de'),
('Marco', 'Haas', 'm.haas@gmx.net'),
('Alina', 'Haas', 'alina.haas@outlook.de'),
('Tobias', 'Schreiber', 'tobias.schreiber@gmx.net'),
('Romy', 'Schreiber', 'romy.s@web.de'),
('Tobias', 'Graf', 't.graf@gmail.com'),
('Romy', 'Graf', 'romy.graf@web.de'),
('Sven', 'Schulte', 'sven.schulte@gmail.com'),
('Luise', 'Schulte', 'luise.s@posteo.de'),
('Sven', 'Dietrich', 's.dietrich@t-online.de'),
('Luise', 'Dietrich', 'luise.dietrich@posteo.de'),
('Timo', 'Ziegler', 'timo.ziegler@t-online.de'),
('Elisa', 'Ziegler', 'elisa.z@outlook.com'),
('Timo', 'Kuhn', 't.kuhn@gmx.de'),
('Elisa', 'Kuhn', 'elisa.kuhn@outlook.com'),
('Marcel', 'Kühn', 'marcel.kuehn@gmx.de'),
('Jule', 'Kühn', 'jule.k@web.de'),
('Marcel', 'Pohl', 'm.pohl@gmail.com'),
('Jule', 'Pohl', 'jule.pohl@web.de'),
('Andreas', 'Engel', 'andreas.engel@gmail.com'),
('Anja', 'Engel', 'anja.e@t-online.de'),
('Andreas', 'Horn', 'a.horn@outlook.de'),
('Anja', 'Horn', 'anja.horn@t-online.de'),
('Kevin', 'Busch', 'kevin.busch@outlook.de'),
('Ronja', 'Busch', 'ronja.b@gmx.net'),
('Kevin', 'Bergmann', 'k.bergmann@web.de'),
('Ronja', 'Bergmann', 'ronja.bergmann@gmx.net'),
('Daniel', 'Voigt', 'daniel.voigt@web.de'),
('Ida', 'Voigt', 'ida.v@gmail.com'),
('Daniel', 'Sauer', 'd.sauer@t-online.de'),
('Ida', 'Sauer', 'ida.sauer@gmail.com'),
('Markus', 'Arnold', 'markus.arnold@t-online.de'),
('Sina', 'Arnold', 'sina.a@outlook.com'),
('Markus', 'Wolff', 'm.wolff@gmx.de'),
('Sina', 'Wolff', 'sina.wolff@outlook.com'),
('Patrick', 'Pfeiffer', 'patrick.pfeiffer@gmx.de'),
('Greta', 'Pfeiffer', 'greta.p@web.de'),
('Patrick', 'Lohmann', 'p.lohmann@gmail.com'),
('Greta', 'Lohmann', 'greta.lohmann@web.de'),
('Robin', 'Beyer', 'robin.beyer@gmail.com'),
('Fiona', 'Beyer', 'fiona.b@t-online.de'),
('Robin', 'Seifert', 'r.seifert@outlook.de'),
('Fiona', 'Seifert', 'fiona.seifert@t-online.de'),
('Christopher', 'Kramer', 'c.kramer@outlook.de'),
('Marina', 'Kramer', 'marina.k@gmx.net'),
('Christopher', 'Jansen', 'christopher.j@web.de'),
('Marina', 'Jansen', 'marina.jansen@gmx.net');
